networks:
  basketball:
    name: basketball
    driver: bridge
    external: true

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    container_name: basketball-devcontainer
    networks:
      basketball:
        aliases:
          - form
    environment:
      NUXT_APP_BASE_URL: "/"
      NUXT_DATABASE_URL: "postgres://root@basketball-database:26257/dev?sslmode=disable"
      NUXT_TOKEN: "your-secret-token"
    volumes:
      - .:/workspace/basketball-form:cached
    tty: true
    stdin_open: true
    command: /bin/bash
  
  migrate-database:
    image: cockroachdb/cockroach:latest-v26.1
    networks:
      basketball:
    volumes:
      - ./migrate.sql:/cockroach/migrate.sql
    command: sql --host basketball-database:26257 --insecure --database dev --file /cockroach/migrate.sql
  
  seed-database:
    image: cockroachdb/cockroach:latest-v26.1
    networks:
      basketball:
    volumes:
      - ./seed.sql:/cockroach/seed.sql
    command: sql --host basketball-database:26257 --insecure --database dev --file /cockroach/seed.sql


  form:
      profiles: ["donotstart"]